spring:

  application:
    name: server
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DRIVER_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate.dialect: ${DIALECT}
      show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  signerKey: ${JWT_SECRET}
  valid-duration: 3600 #in-seconds
  refreshable-duration: 36000 #in-seconds
server:
  port: 6969
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-ui.html
