version: '3.3'
services:
  mysql:
    image: mysql:9.3.0
    container_name: db_container
    restart: always
    environment:
      MYSQL_DATABASE: DB-HUIT-LIBRARY
      MYSQL_ROOT_PASSWORD: 'sa123'
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3310:3306"
    volumes:
      - db-data:/var/lib/mysqld
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - server

  java-app:
    image: eclipse-temurin:17-jdk-alpine
    container_name: java_app_container
    working_dir: /app
    volumes:
      - ./:/app
    command: ["./mvnw", "spring-boot:run"]
    depends_on:
      - mysql
      - redis
    ports:
      - "6969:6969"
    networks:
      - server

  redis:
    image: redis:7.0-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - server

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "90:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/usr/share/nginx/html
    depends_on:
      - java-app
    networks:
      - server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_library
    restart: always
    depends_on:
      - mysql
    ports:
      - "100:80"
    environment:
      PMA_HOST: db_container
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - server

volumes:
  db-data:
  redis-data:

networks:
  server:
    driver: bridge
